<?php
declare(strict_types=1);

// BranchAggregate SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BranchAggregateUtility::setRegistrar(function (BranchAggregateUtility $u): void {
    $u->clean = [BranchAggregateClean::class, 'call'];
    $u->done = [BranchAggregateDone::class, 'call'];
    $u->make_error = [BranchAggregateMakeError::class, 'call'];
    $u->feature_add = [BranchAggregateFeatureAdd::class, 'call'];
    $u->feature_hook = [BranchAggregateFeatureHook::class, 'call'];
    $u->feature_init = [BranchAggregateFeatureInit::class, 'call'];
    $u->fetcher = [BranchAggregateFetcher::class, 'call'];
    $u->make_fetch_def = [BranchAggregateMakeFetchDef::class, 'call'];
    $u->make_context = [BranchAggregateMakeContext::class, 'call'];
    $u->make_options = [BranchAggregateMakeOptions::class, 'call'];
    $u->make_request = [BranchAggregateMakeRequest::class, 'call'];
    $u->make_response = [BranchAggregateMakeResponse::class, 'call'];
    $u->make_result = [BranchAggregateMakeResult::class, 'call'];
    $u->make_point = [BranchAggregateMakePoint::class, 'call'];
    $u->make_spec = [BranchAggregateMakeSpec::class, 'call'];
    $u->make_url = [BranchAggregateMakeUrl::class, 'call'];
    $u->param = [BranchAggregateParam::class, 'call'];
    $u->prepare_auth = [BranchAggregatePrepareAuth::class, 'call'];
    $u->prepare_body = [BranchAggregatePrepareBody::class, 'call'];
    $u->prepare_headers = [BranchAggregatePrepareHeaders::class, 'call'];
    $u->prepare_method = [BranchAggregatePrepareMethod::class, 'call'];
    $u->prepare_params = [BranchAggregatePrepareParams::class, 'call'];
    $u->prepare_path = [BranchAggregatePreparePath::class, 'call'];
    $u->prepare_query = [BranchAggregatePrepareQuery::class, 'call'];
    $u->graphql_body = [BranchAggregateGraphql::class, 'body'];
    $u->graphql_errors = [BranchAggregateGraphql::class, 'errors'];
    $u->result_basic = [BranchAggregateResultBasic::class, 'call'];
    $u->result_body = [BranchAggregateResultBody::class, 'call'];
    $u->result_headers = [BranchAggregateResultHeaders::class, 'call'];
    $u->transform_request = [BranchAggregateTransformRequest::class, 'call'];
    $u->transform_response = [BranchAggregateTransformResponse::class, 'call'];
});
